function [ ForceUCAF,ForceUCAR,ForceLCAF,ForceLCAR,ForceSHOCK,ForceTOE ] = LinkForce( Fx, Fy, Fz, Mx, My, Mz, UCAF,UCAR,UCAO,LCAF,LCAR,LCAO,SHOCKO,SHOCKI,TOEI,TOEO,TIRECP )
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here


VectorUCAF = UCAF - UCAO;
VectorUCAR = UCAR - UCAO;
VectorLCAF = LCAF - LCAO;
VectorLCAR = LCAR - LCAO;
VectorSHOCK = SHOCKI - SHOCKO;
VectorTOE = TOEI - TOEO;

MArmUCAF = TIRECP - UCAO;
MArmUCAR = TIRECP - UCAO;
MArmLCAF = TIRECP - LCAO;
MArmLCAR = TIRECP - LCAO;
MArmSHOCK = TIRECP - SHOCKO;
MArmTOE = TIRECP - TOEO;

UnitUCAF = VectorUCAF/norm(VectorUCAF);
UnitUCAR = VectorUCAR/norm(VectorUCAR);
UnitLCAF = VectorLCAF/norm(VectorLCAF);
UnitLCAR = VectorLCAR/norm(VectorLCAR);
UnitSHOCK = VectorSHOCK/norm(VectorSHOCK);
UnitTOE = VectorTOE/norm(VectorTOE);

B = -[Fx;Fy;Fz;Mx;My;Mz];

A = [ 
      % Sum of forces X
      UnitUCAF(1),...
      UnitUCAR(1),...
      UnitLCAF(1),...
      UnitLCAR(1),...
      UnitSHOCK(1),...
      UnitTOE(1);...
      % Sum of forces Y
      UnitUCAF(2),...
      UnitUCAR(2),...
      UnitLCAF(2),...
      UnitLCAR(2),...
      UnitSHOCK(2),...
      UnitTOE(2);...
      % Sum of forces Z
      UnitUCAF(3),...
      UnitUCAR(3),...
      UnitLCAF(3),...
      UnitLCAR(3),...
      UnitSHOCK(3),...
      UnitTOE(3);...
      % Sum of moments about X
      -MArmUCAF(3)*UnitUCAF(2)+MArmUCAF(2)*UnitUCAF(3),...
      -MArmUCAR(3)*UnitUCAR(2)+MArmUCAR(2)*UnitUCAR(3),...
      -MArmLCAF(3)*UnitLCAF(2)+MArmLCAF(2)*UnitLCAF(3),...
      -MArmLCAR(3)*UnitLCAR(2)+MArmLCAR(2)*UnitLCAR(3),...
      -MArmSHOCK(3)*UnitSHOCK(2)+MArmSHOCK(2)*UnitSHOCK(3),...
      -MArmTOE(3)*UnitTOE(2)+MArmTOE(2)*UnitTOE(3);...
      % Sum of moments about Y
      MArmUCAF(3)*UnitUCAF(1)-MArmUCAF(1)*UnitUCAF(3),...
      MArmUCAR(3)*UnitUCAR(1)-MArmUCAR(1)*UnitUCAR(3),...
      MArmLCAF(3)*UnitLCAF(1)-MArmLCAF(1)*UnitLCAF(3),...
      MArmLCAR(3)*UnitLCAR(1)-MArmLCAR(1)*UnitLCAR(3),...
      MArmSHOCK(3)*UnitSHOCK(1)-MArmSHOCK(1)*UnitSHOCK(3),...
      MArmTOE(3)*UnitTOE(1)-MArmTOE(1)*UnitTOE(3);...
      % Sum of moments about Z
      -MArmUCAF(2)*UnitUCAF(1)+MArmUCAF(1)*UnitUCAF(2),...
      -MArmUCAR(2)*UnitUCAR(1)+MArmUCAR(1)*UnitUCAR(2),...
      -MArmLCAF(2)*UnitLCAF(1)+MArmLCAF(1)*UnitLCAF(2),...
      -MArmLCAR(2)*UnitLCAR(1)+MArmLCAR(1)*UnitLCAR(2),...
      -MArmSHOCK(2)*UnitSHOCK(1)+MArmSHOCK(1)*UnitSHOCK(2),...
      -MArmTOE(2)*UnitTOE(1)+MArmTOE(1)*UnitTOE(2);...
      ];
      
      
      X = A\B;
      
      ForceUCAF = X(1);
      ForceUCAR = X(2);
      ForceLCAF = X(3);
      ForceLCAR = X(4);
      ForceSHOCK = X(5);
      ForceTOE = X(6);
      
      ForceVectorUCAF = ForceUCAF.*UnitUCAF;
      ForceVectorUCAR = ForceUCAR.*UnitUCAR;
      ForceVectorLCAF = ForceLCAF.*UnitLCAF;
      ForceVectorLCAR = ForceLCAR.*UnitLCAR;
      ForceVectorSHOCK = ForceSHOCK.*UnitSHOCK;
      ForceVectorTOE = ForceTOE.*UnitTOE;
      
      MomentCheck = cross(MArmUCAF,ForceVectorUCAF)+...
          cross(MArmUCAR,ForceVectorUCAR)+...
          cross(MArmLCAF,ForceVectorLCAF)+...
          cross(MArmLCAR,ForceVectorLCAR)+...
          cross(MArmSHOCK,ForceVectorSHOCK)+...
          cross(MArmTOE,ForceVectorTOE) + [Mx My Mz];
      
      ForceCheck = ForceVectorUCAF + ForceVectorUCAR + ForceVectorLCAF +...
          ForceVectorLCAR + ForceVectorSHOCK + ForceVectorTOE + [Fx Fy Fz];
      


end

